3

In [1]:
import glob,os,numpy as np
import cPickle as pickle
#Please install Biopython via: pip install Biopython
import LibraryDesigner as ld
import LibraryTools as lt

In [3]:
reload(ld)

<module 'LibraryDesigner' from 'LibraryDesigner.pyc'>

In [5]:
reload(ld)

<module 'LibraryDesigner' from 'LibraryDesigner.py'>

In [8]:
genome_folder = r'C:\Data\Genomes\HumanGenome\hg38'
save_file=genome_folder+os.sep+'allgenome_17mer_sparse.npz'
ct = ld.countTable(word=17,save_file=save_file)

files = glob.glob(genome_folder+os.sep+'*.fa')

for fl in np.setdiff1d(files,dic_info['files']):
    names,seqs = lt.fastaread(fl)
    for nm,sq in zip(names,seqs):
        print nm
        ct.consume(sq,verbose=True)
ct.complete(verbose=True)
ct.save()

chr1
Time to compute seq2Int: 52.6410000324
chr10
Time to compute seq2Int: 37.6809999943
chr10_GL383545v1_alt
Time to compute seq2Int: 0.0799999237061
chr10_GL383546v1_alt
Time to compute seq2Int: 0.134999990463
chr10_KI270824v1_alt
Time to compute seq2Int: 0.0709998607635
chr10_KI270825v1_alt
Time to compute seq2Int: 0.114000082016
chr11
Time to compute seq2Int: 46.368999958
chr11_GL383547v1_alt
Time to compute seq2Int: 0.058000087738
chr11_JH159136v1_alt
Time to compute seq2Int: 0.055999994278
chr11_JH159137v1_alt
Time to compute seq2Int: 0.0810000896454
chr11_KI270721v1_random
Time to compute seq2Int: 0.0609998703003
chr11_KI270826v1_alt
Time to compute seq2Int: 0.0789999961853
chr11_KI270827v1_alt
Time to compute seq2Int: 0.0210001468658
chr11_KI270829v1_alt
Time to compute seq2Int: 0.0940001010895
chr11_KI270830v1_alt
Time to compute seq2Int: 0.0750000476837
chr11_KI270831v1_alt
Time to compute seq2Int: 0.116999864578
chr11_KI270832v1_alt
Time to compute seq2Int: 0.0610001087189
c

AttributeError: 'module' object has no attribute 'save_npz'

In [29]:
ints = np.array(ct.ints,dtype='uint64')

In [34]:
np.savez_compressed(save_file.replace('.npz','_uncounted.npz'), ints=ints)

In [33]:
save_file.replace('.npz','_uncounted.npz')

'C:\\Data\\Genomes\\HumanGenome\\hg38\\allgenome_17mer_sparse_uncounted.npz'

In [2]:
import numpy as np

In [1]:
import numpy as np
intsf = np.load('C:\\Data\\Genomes\\HumanGenome\\hg38\\allgenome_17mer_sparse_uncounted.npz')
ints = intsf['ints']

In [2]:
pos,cts = np.unique(ints,return_counts=True)

In [3]:
countTable_values = np.array(np.clip(cts, 0, 2**16-1),dtype='uint16')

In [4]:
pos[:50],cts[:50],countTable_values[:50]

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       dtype=uint64),
 array([160801887,     22864,    114363,     43847,     12539,      7676,
             1030,      6504,     75104,     15404,     23205,     20870,
            10237,     11350,      6610,     25976,      8373,      2666,
             3471,      1305,      3463,      2771,       292,      2675,
              481,       209,       331,       186,      2488,      1462,
             1580,      2469,     56426,      7902,     13140,     10438,
             7030,      5392,       719,      4404,     12586,      6265,
             3126,      4496,      7539,      4851,      5193,      7334,
             1705,      3334], dtype=int64),
 array([65535, 22864, 65535, 43847, 12539,  7676,  1030,  6504, 65535,
        15404, 23205, 20870, 10237, 11350,  6

In [6]:
import scipy.sparse as ss

In [7]:
word=17
max_size = 4**word
max_sparse_ind = 2**31#scipy.sparse decided to encoded in indeces in int32. Correct!
nrows = max_size/max_sparse_ind
matrix = ss.lil_matrix((nrows,max_sparse_ind), dtype=np.uint16)
pos_col = pos/max_sparse_ind
pos_row = pos-pos_col*max_sparse_ind
matrix[pos_col,pos_row] = countTable_values

In [10]:
matrix_ = matrix.tocsr()

In [25]:
matrix_

43847

In [14]:
ss.save_npz(r'C:\Data\Genomes\HumanGenome\hg38\allgenome_17mer_sparse.npz',matrix_)

In [2]:
import scipy.sparse as ss
matrix = ss.load_npz(r'C:\Data\Genomes\HumanGenome\hg38\allgenome_17mer_sparse.npz')

In [18]:
pos_x,pos_y=np.random.randint(0,8,10),np.random.randint(0,10**8,10)
import time
start=time.time()
matrix.A[pos_x,pos_y]
end=time.time()
print end-start

13.8249998093


In [19]:
matrix_ = matrix.A

In [22]:
pos_x,pos_y=np.random.randint(0,8,1000),np.random.randint(0,10**8,1000)
matrix_[pos_x,pos_y]

array([  0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,   0,
         0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   1,   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,
         1,   0,   0,   0,   0,   0,   0,   0,   0,   2,   0,   0,   0,
         0,   1,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,
         0,   0,   2,   6,   0,   0,   0,   1,   0,   0,   0,   0,   0,
         0,   1,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   2,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   1,   2,   1,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   2,   0,   0,   0,   0,   0,   

In [7]:
import numpy as np
pos_x,pos_y=np.random.randint(0,8,100),np.random.randint(0,10**8,100)
pos_x

array([5, 5, 4, 1, 3, 2, 3, 6, 5, 4, 4, 2, 5, 3, 6, 1, 7, 4, 3, 3, 6, 6,
       7, 2, 6, 6, 4, 7, 5, 7, 1, 4, 7, 4, 0, 4, 3, 0, 2, 3, 4, 3, 5, 6,
       2, 5, 0, 4, 1, 2, 3, 1, 0, 1, 4, 0, 0, 7, 7, 5, 6, 6, 5, 6, 4, 0,
       7, 7, 2, 3, 6, 0, 6, 0, 5, 1, 4, 7, 0, 5, 1, 0, 1, 7, 0, 3, 1, 5,
       4, 4, 2, 7, 4, 0, 2, 7, 0, 1, 2, 0])

In [6]:
genome_folder = r'C:\Data\Genomes\HumanGenome\hg38'
save_file=genome_folder+os.sep+'allgenome_17mer_sparse.npz'
info_file=save_file.replace('.npz','.inf')
temp_file = save_file.replace('.npz','_temp.npz')
ct = ld.countTable(word=17,save_file=save_file)
dic_info={'files':[]}
if os.path.exists(save_file) and :
    dic_info = pickle.load(open(info_file,'rb'))
    ct.ints = list(np.load(temp_file)['ints'])
files = glob.glob(genome_folder+os.sep+'*.fa')

for fl in np.setdiff1d(files,dic_info['files']):
    names,seqs = lt.fastaread(fl)
    for nm,sq in zip(names,seqs):
        print nm
        ct.consume(sq,verbose=True)
    np.savez_compressed(temp_file, ints=ct.ints)
    dic_info['files'].append(fl)
    pickle.dump(dic_info,open(info_file,'wb'))
ct.complete(verbose=True)
ct.save()

chr1
Time to compute seq2Int: 88.2249999046


NameError: name 'self' is not defined

In [7]:
np.savez_compressed(temp_file, ints=ct.ints)

In [35]:
bases = ['A','G','C','T']
sq = ''.join([np.random.choice(bases) for _ in range(10**6)])


In [34]:
ct = ld.countTable(word=17,save_file=None)
ct.consume(sq)

Time to compute seq2Int: 0.128999948502
Time to compute unique: 0.176000118256
Time to compute clipping: 0.0739998817444
Time to update matrix: 0.186000108719


In [36]:
ct.consume(sq)

Time to compute seq2Int: 0.130000114441
Time to compute unique: 0.175999879837
Time to compute clipping: 0.242000102997
Time to update matrix: 75.754999876


In [ ]:
#Construct count table of 17-mers across the genome/transcriptome

In [6]:
files[20]

'C:\\Data\\Genomes\\HumanGenome\\hg38\\chr12.fa'

In [25]:
from LibraryConstruction import nt2intblock
from LibraryConstruction import nt2intblock_rc

In [27]:
import LibraryConstruction as lc
seq = 'TCGagatcgtaNASTtA'
seq2Int_rc(seq),seq2Int(lc.seqrc(seq)),nt2intblock(seq[::-1])

(12938481112L, 12938481112L, 691743688246)

In [28]:
help(nt2intblock)

Help on function nt2intblock in module LibraryConstruction:

nt2intblock(gen_seq)



In [2]:
%timeit for _ in range(1000): seq2Int('TCGagatcgtaNASTTA')

10000 loops, best of 3: 116 µs per loop


In [6]:
bases = ['A','G','C','T']
sq = ''.join([np.random.choice(bases) for _ in range(10**6)])

In [5]:
ct = countTable(word=17)
ct.update_countTable(sq)
#ct.get(sq[:17])

In [7]:
ct.update_countTable(sq)

In [11]:
ss.save_npz('test_matrix.npz',ct.matrix.tocsr())

In [14]:
mat = ss.load_npz('test_matrix.npz')
mat.tolil()

<8x2147483648 sparse matrix of type '<type 'numpy.uint16'>'
	with 2999717 stored elements in LInked List format>

In [74]:
%load_ext Cython

The Cython extension is already loaded. To reload it, use:
  %reload_ext Cython


In [90]:
%%cython
cimport numpy as np
ctypedef np.uint64_t uint64_t

cdef uint64_t BASE_TO_BIN_LUT[128]
BASE_TO_BIN_LUT[:] = [0,0,0,0,0,0,0,0,# 7
    0,0,0,0,0,0,0,0, # 15
    0,0,0,0,0,0,0,0, # 23
    0,0,0,0,0,0,0,0, # 31
    0,0,0,0,0,0,0,0, # 39
    0,0,0,0,0,0,0,0, # 47
    0,0,0,0,0,0,0,0, # 55
    0,0,0,0,0,0,0,0, # 63
    0,0,0,1,0,0,0,2, # 71
    0,0,0,0,0,0,0,0, # 79
    0,0,0,0,3,0,0,0, # 87
    0,0,0,0,0,0,0,0, # 95
    0,0,0,1,0,0,0,2, # 103
    0,0,0,0,0,0,0,0, # 111
    0,0,0,0,3,0,0,0, # 119
    0,0,0,0,0,0,0,0]
cdef uint64_t BASE_TO_BIN_LUT_RC[128]
BASE_TO_BIN_LUT_RC[:] = [0,0,0,0,0,0,0,0,# 7
    0,0,0,0,0,0,0,0, # 15
    0,0,0,0,0,0,0,0, # 23
    0,0,0,0,0,0,0,0, # 31
    0,0,0,0,0,0,0,0, # 39
    0,0,0,0,0,0,0,0, # 47
    0,0,0,0,0,0,0,0, # 55
    0,0,0,0,0,0,0,0, # 63
    0,3,0,2,0,0,0,1, # 71
    0,0,0,0,0,0,0,0, # 79
    0,0,0,0,0,0,0,0, # 87
    0,0,0,0,0,0,0,0, # 95
    0,3,0,2,0,0,0,1, # 103
    0,0,0,0,0,0,0,0, # 111
    0,0,0,0,0,0,0,0, # 119
    0,0,0,0,0,0,0,0]


def seq2Int(char *seq):
    cdef int length = len(seq)
    cdef uint64_t seqint = 0
    cdef int i
    
    for i in range(length):
        seqint <<= 2
        seqint|=BASE_TO_BIN_LUT[seq[i]]
    return seqint
def seq2Int_rc(char *seq):
    cdef int length = len(seq)
    cdef uint64_t seqint = 0
    cdef int i
    
    for i in range(length):
        seqint <<= 2
        seqint|=BASE_TO_BIN_LUT_RC[seq[length-i-1]]
    return seqint

In [97]:
!python C_Tools\setup.py build_ext --inplace

Compiling C_Tools\seqint.pyx because it changed.
[1/1] Cythonizing C_Tools\seqint.pyx
running build_ext
building 'seqint' extension
C:\Users\Bogdan\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\Bogdan\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\Bogdan\Anaconda2\include -IC:\Users\Bogdan\Anaconda2\PC /TcC_Tools\seqint.c /Fobuild\temp.win-amd64-2.7\Release\C_Tools\seqint.obj
seqint.c
c:\users\bogdan\anaconda2\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
C_Tools\seqint.c(1232) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
C_Tools\seqint.c(1358) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
C:\Users\Bogdan\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.

In [60]:
c_lib_folder = distutils.msvc9compiler.find_vcvarsall(distutils.msvc9compiler.VERSION).replace('vcvarsall.bat','VC\include')

'C:\\Users\\Bogdan\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\include'

In [3]:
sq = 'A'.join(['G'*17]*2**17)

In [ ]:
bases = ['A','G','C','T','N']
sq = ''.join([np.random.choice(bases) for _ in range(40*10**6)])

In [11]:
ct = countTable(word=17)
ct.update_countTable(sq)
ct.get(sq[:17])

1

In [12]:
ct.matrix.getnnz()

999780

In [11]:
ct.save_file = 'sparse_matrix.npz'
ct.saveTable()

NotImplementedError: Save is not implemented for sparse matrix of format lil.

In [12]:
ct.csr_matrix = ct.matrix.tocsr()

In [18]:
4**17/(3*10**9)

5L

In [15]:
ct.csr_matrix.getnnz()

999955

In [ ]:
from libnano.seqint import seq2Int
import os
import numpy as np
import glob
files = glob.glob(r'C:\Data\Genomes\HumanGenome\hg38\*.fa')
word = 17
batch = 1000000

fp = ss.lil_matrix((1,4**17), dtype=np.uint16)

for file_ in np.array(files):
    names,seqs=fastaread(file_)
    for nm,sq in zip(names,seqs):
        
        for isq in range(int(len(sq)/batch)+1):
            print([nm,isq*batch])
            sq_ = sq[isq*batch:(isq+1)*batch]
            sq_word = [sq_[i:i+word] for i in range(len(sq_)-word)]
            ints = list(map(seq2Int,sq_word))
            pos,cts = np.unique(ints,return_counts=True)
            ints_vals = np.array(fp[pos],dtype='uint64')
            ints_vals_ = np.array(np.clip(ints_vals+cts, 0, 2**16-1),dtype='uint16')
            fp[pos] = ints_vals_
fl = r'C:\Data\Genomes\HumanGenome\hg38\allgenome_17w.npy'
fid = open(fl,'wb')
fid.write(fp.tobytes())
fid.close()

In [84]:
import scipy.sparse as ss

mtx[10]=1


OverflowError: Python int too large to convert to C long

In [30]:
import numpy as np
word=16
base = 4**(np.arange(word,dtype='uint64')[::-1])
def seq2Int3(seq):
    #dic_conv = {'C':1,'c':1,'G':2,'g':2,'T':3,'t':3}
    #digits = np.array([dic_conv.get(let,0) for let in seq],dtype='uint64')
    word = len(seq)
    digits = np.zeros(word,dtype='uint64')
    count = 0
    for let in seq:
        if let=='C':
            digits[count]=1
        elif let=='c':
            digits[count]=1
        elif let=='G':
            digits[count]=2
        elif let=='g':
            digits[count]=2
        elif let=='T':
            digits[count]=3
        elif let=='t':
            digits[count]=3
        count+=1
    #base = 4**(np.arange(word,dtype='uint64')[::-1])
    return np.sum(base*digits)

In [15]:
seq2Int3('CATAGGTadasaAA')

80396288

In [80]:
import scipy.sparse as ss
mtx = ss.lil_matrix((1,4**17), dtype=np.uint16)
mtx[0,10]=1


matrix([[1, 0, 1]], dtype=uint16)

In [71]:
help(ss.lil_matrix)

Help on class lil_matrix in module scipy.sparse.lil:

class lil_matrix(scipy.sparse.base.spmatrix, scipy.sparse.sputils.IndexMixin)
 |  Row-based linked list sparse matrix
 |  
 |  This is a structure for constructing sparse matrices incrementally.
 |  Note that inserting a single item can take linear time in the worst case;
 |  to construct a matrix efficiently, make sure the items are pre-sorted by
 |  index, per row.
 |  
 |  This can be instantiated in several ways:
 |      lil_matrix(D)
 |          with a dense matrix or rank-2 ndarray D
 |  
 |      lil_matrix(S)
 |          with another sparse matrix S (equivalent to S.tolil())
 |  
 |      lil_matrix((M, N), [dtype])
 |          to construct an empty matrix with shape (M, N)
 |          dtype is optional, defaulting to dtype='d'.
 |  
 |  Attributes
 |  ----------
 |  dtype : dtype
 |      Data type of the matrix
 |  shape : 2-tuple
 |      Shape of the matrix
 |  ndim : int
 |      Number of dimensions (this is always 2)
 |  n

In [81]:
print "hello"

hello


In [55]:
import os
from tempfile import mkstemp

import numpy as np
import scipy.sparse as ss
import h5sparse
reload(h5sparse)


h5_path = mkstemp(suffix=".h5")[1]
sparse_matrix = ss.csr_matrix([[0, 1, 0],
                               [0, 0, 1],
                               [0, 0, 0],
                               [1, 1, 0]],
                              dtype=np.float64)
with h5sparse.File(h5_path) as h5f:
    h5f.create_dataset('sparse/matrix', data=sparse_matrix)
    
h5f = h5sparse.File(h5_path)
h5f['sparse']['matrix'][1]

(1.0, 1, 2)

In [ ]:
csr_matrix((1,1000),)

In [44]:
>>> indptr = np.array([0, 2, 3, 6])
>>> indices = np.array([0, 2, 2, 0, 1, 2])
>>> data = np.array([1, 2, 3, 4, 5, 6])
>>> csr_matrix((data, indices, indptr), shape=(3, 3)).toarray()
array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])


In [56]:
help(ss.csr)

Help on module scipy.sparse.csr in scipy.sparse:

NAME
    scipy.sparse.csr - Compressed Sparse Row matrix format

FILE
    c:\users\bogda\anaconda2\lib\site-packages\scipy\sparse\csr.py

CLASSES
    scipy.sparse.compressed._cs_matrix(scipy.sparse.data._data_matrix, scipy.sparse.data._minmax_mixin, scipy.sparse.sputils.IndexMixin)
        csr_matrix(scipy.sparse.compressed._cs_matrix, scipy.sparse.sputils.IndexMixin)
    scipy.sparse.sputils.IndexMixin(__builtin__.object)
        csr_matrix(scipy.sparse.compressed._cs_matrix, scipy.sparse.sputils.IndexMixin)
    
    class csr_matrix(scipy.sparse.compressed._cs_matrix, scipy.sparse.sputils.IndexMixin)
     |  Compressed Sparse Row matrix
     |  
     |  This can be instantiated in several ways:
     |      csr_matrix(D)
     |          with a dense matrix or rank-2 ndarray D
     |  
     |      csr_matrix(S)
     |          with another sparse matrix S (equivalent to S.tocsr())
     |  
     |      csr_matrix((M, N), [dtype])
     | 

In [34]:
isinstance(10, int)

True

In [15]:
import os
from tempfile import mkstemp

import numpy as np
import scipy.sparse as ss
import h5sparse



h5_path = mkstemp(suffix=".h5")[1]
sparse_matrix = ss.csr_matrix([[0, 1, 0],
                               [0, 0, 1],
                               [0, 0, 0],
                               [1, 1, 0]],
                              dtype=np.float64)
with h5sparse.File(h5_path) as h5f:
    h5f.create_dataset('sparse/matrix', data=sparse_matrix)
with h5sparse.File(h5_path) as h5f:
    assert 'sparse' in h5f
    assert 'matrix' in h5f['sparse']
    assert (h5f['sparse']['matrix'][1:3] != sparse_matrix[1:3]).size == 0
    assert (h5f['sparse']['matrix'][2:] != sparse_matrix[2:]).size == 0
    assert (h5f['sparse']['matrix'][:2] != sparse_matrix[:2]).size == 0
    assert (h5f['sparse']['matrix'][-2:] != sparse_matrix[-2:]).size == 0
    assert (h5f['sparse']['matrix'][:-2] != sparse_matrix[:-2]).size == 0
    assert (h5f['sparse']['matrix'].value != sparse_matrix).size == 0

os.remove(h5_path)

WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\bogda\\appdata\\local\\temp\\tmp7khfjw.h5'

In [16]:
os.remove(h5_path)

WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\bogda\\appdata\\local\\temp\\tmp7khfjw.h5'

In [14]:
import six

In [13]:
import scipy.sparse as sp
import numpy as np
vec = sp.csc_matrix((10,1), dtype=np.int8)


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int8)

In [2]:
from libnano.seqint import seq2Int

In [16]:
seq2Int('CATAGGTadasaAA')

80396288

In [3]:
from tqdm import tqdm_notebook as tqdm

In [17]:
word=17
base = 4**(np.arange(word)[::-1])
print(type(base[0]))

<class 'numpy.int32'>


In [9]:
from libnano.seqint import seq2Int
seq2Int('AAAC'),seq2Int('CAAA')

(1, 64)

In [5]:
def fastaread(fl,force_upper=False):
    fid = open(fl,'r')
    names = []
    seqs = []
    lines = []
    while True:
        line = fid.readline()
        if not line:
            seq = "".join(lines)
            if force_upper:
                seq=seq.upper()
            seqs.append(seq)
            break
        if line[0]=='>':
            name = line[1:-1]
            names.append(name)
            seq = "".join(lines)
            if force_upper:
                seq=seq.upper()
            seqs.append(seq)
            lines = []
        else:
            lines.append(line[:-1])
    fid.close()
    return [names,seqs[1:]]

### Map the genome

In [25]:
from libnano.seqint import seq2Int
import os
import numpy as np
import glob
files = glob.glob(r'C:\Data\Genomes\HumanGenome\hg38\*.fa')
word = 17
batch = 1000000

for file_ in np.array(files):
    names,seqs=fastaread(file_)
    for nm,sq in zip(names,seqs):    
        fp = np.zeros(4**word,dtype='uint16')
        for isq in range(int(len(sq)/batch)+1):
            print([nm,isq*batch])
            sq_ = sq[isq*batch:(isq+1)*batch]
            sq_word = [sq_[i:i+word] for i in range(len(sq_)-word)]
            ints = list(map(seq2Int,sq_word))
            pos,cts = np.unique(ints,return_counts=True)
            ints_vals = np.array(fp[pos],dtype='uint64')
            ints_vals_ = np.array(np.clip(ints_vals+cts, 0, 2**16-1),dtype='uint16')
            fp[pos] = ints_vals_
fl = r'C:\Data\Genomes\HumanGenome\hg38\allgenome_17w.npy'
fid = open(fl,'wb')
fid.write(fp.tobytes())
fid.close()

['chr1', 0]
['chr1', 1000000]
['chr1', 2000000]
['chr1', 3000000]
['chr1', 4000000]
['chr1', 5000000]
['chr1', 6000000]
['chr1', 7000000]
['chr1', 8000000]
['chr1', 9000000]
['chr1', 10000000]
['chr1', 11000000]
['chr1', 12000000]
['chr1', 13000000]
['chr1', 14000000]
['chr1', 15000000]
['chr1', 16000000]
['chr1', 17000000]
['chr1', 18000000]
['chr1', 19000000]
['chr1', 20000000]
['chr1', 21000000]
['chr1', 22000000]
['chr1', 23000000]
['chr1', 24000000]
['chr1', 25000000]
['chr1', 26000000]
['chr1', 27000000]
['chr1', 28000000]
['chr1', 29000000]
['chr1', 30000000]
['chr1', 31000000]
['chr1', 32000000]
['chr1', 33000000]
['chr1', 34000000]
['chr1', 35000000]
['chr1', 36000000]
['chr1', 37000000]
['chr1', 38000000]
['chr1', 39000000]
['chr1', 40000000]
['chr1', 41000000]
['chr1', 42000000]
['chr1', 43000000]
['chr1', 44000000]
['chr1', 45000000]
['chr1', 46000000]
['chr1', 47000000]
['chr1', 48000000]
['chr1', 49000000]
['chr1', 50000000]
['chr1', 51000000]
['chr1', 52000000]
['chr1', 

In [ ]:
fp = np.memmap(fl, dtype='uint16', mode='r', shape=4**word)

### Map the transcriptome

In [ ]:
from libnano.seqint import seq2Int
import os
import numpy as np
import glob
files = glob.glob(r'C:\Data\Genomes\HumanGenome\hg38\*.fa')
word = 17
batch = 1000000

for file_ in np.array(files):
    names,seqs=fastaread(file_)
    for nm,sq in zip(names,seqs):    
        fp = np.zeros(4**word,dtype='uint16')
        for isq in range(int(len(sq)/batch)+1):
            print([nm,isq*batch])
            sq_ = sq[isq*batch:(isq+1)*batch]
            sq_word = [sq_[i:i+word] for i in range(len(sq_)-word)]
            ints = list(map(seq2Int,sq_word))
            pos,cts = np.unique(ints,return_counts=True)
            ints_vals = np.array(fp[pos],dtype='uint64')
            ints_vals_ = np.array(np.clip(ints_vals+cts, 0, 2**16-1),dtype='uint16')
            fp[pos] = ints_vals_
fl = r'C:\Data\Genomes\HumanGenome\hg38\allgenome_17w.npy'
fid = open(fl,'wb')
fid.write(fp.tobytes())
fid.close()